npm i @libsql/client drizzle-orm oslo dotenv

npm install -D drizzle-kit
npm i -D drizzle-kit
npm install drizzle-kit studio
npm install milligram
npm install uuid
npm i --save-dev @types/uuid
npm install -D @ngneat/falso
npm install typescript --save-dev


//npm i -D drizzle-studio
// ??npm i --save-dev @types/libsql

barburator-dev

libsql://barburator-dev-visigoth21.turso.io

DB_URL = "libsql://barburator-dev-visigoth21.turso.io"
DB_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MjAwMzM3MTAsImlkIjoiZWIwZmFjYzgtYjc5My00MTYzLTg3OWUtZDU0YWZjMmQ0YmE5In0.I0lNHzo5o1_aNwTiqH7hDuLwFrAPm-DuZ6w5tiJw_LCBz8jZzAbRbzljNEZXiQnDCOPeJOJDFjT0KBc0RDcJBg"
DB_NAME = "barburator-dev"